# Generated by Django 2.1.5 on 2019-02-04 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='sgrs_notified_on',
            new_name='sgrs_responded_on',
        ),
        migrations.AlterField(
            model_name='case',
            name='sgrs_responded_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='SGRS Responded On'),
        ),
        migrations.AddField(
            model_name='case',
            name='sgrs_service_num',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
