# Generated by Django 2.2.2 on 2019-06-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='asr',
            field=models.PositiveIntegerField(db_index=True, unique=True, verbose_name='ASR Num.'),
        ),
    ]
