# Generated by Django 2.1.5 on 2019-02-04 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_alter_sgrs_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='is_federal',
            field=models.BooleanField(null=True),
        ),
    ]
