# Generated by Django 2.2.2 on 2019-06-20 19:15

import cases.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_import_data', '0005_auto_20190619_1532'),
        ('cases', '0002_auto_20190619_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('data_source', models.CharField(choices=[('web', 'Web'), ('excel', 'Excel'), ('access_prelim_technical', 'Access Prelim. Technical Table'), ('access_technical', 'Access Technical Table'), ('access_prelim_application', 'Access Prelim. Application Table'), ('access_application', 'Access Application Table'), ('nam_application', 'NRQZ Analyzer Application'), ('fcc_asr', 'FCC ASR Database')], default='web', help_text='The source that this object was created from', max_length=25)),
                ('comments', cases.models.SensibleTextField(blank=True)),
                ('model_import_attempt', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_import_data.ModelImportAttempt')),
            ],
            options={
                'verbose_name': 'Case Group',
                'verbose_name_plural': 'Case Groups',
            },
        ),
    ]
