# Generated by Django 2.1.5 on 2019-02-05 17:23

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_case_is_federal'),
    ]

    operations = [
        migrations.AddField(
            model_name='preliminarycase',
            name='is_federal',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='agl',
            field=models.FloatField(blank=True, help_text='Facility height to center above ground level, in meters', null=True, verbose_name='AGL (meters)'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='amsl',
            field=models.FloatField(blank=True, help_text='Facility ground elevation, in meters', null=True, verbose_name='AMSL (meters)'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='az_bearing',
            field=models.CharField(blank=True, help_text='The Azimuth bearing between the Facility and the GBT, as imported from existing data', max_length=256, null=True, verbose_name='AZ bearing degrees True'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='calc_az',
            field=models.FloatField(blank=True, help_text="Azimuth bearing between the Facility and the GBT, as calculated based on this Facility's, location", null=True, verbose_name='Calculated Azimuth Bearing (°)'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='call_sign',
            field=models.CharField(blank=True, help_text='The radio call sign of the Facility', max_length=256, null=True, verbose_name='Call Sign'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='fcc_file_number',
            field=models.CharField(blank=True, help_text='???', max_length=256, null=True, verbose_name='FCC File Number'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text='A physical location on the Earth', null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='facility',
            name='site_num',
            field=models.PositiveIntegerField(blank=True, help_text='???', null=True, verbose_name='Site #'),
        ),
        migrations.AlterField(
            model_name='preliminaryfacility',
            name='agl',
            field=models.FloatField(blank=True, help_text='Facility height to center above ground level, in meters', null=True, verbose_name='AGL (meters)'),
        ),
        migrations.AlterField(
            model_name='preliminaryfacility',
            name='amsl',
            field=models.FloatField(blank=True, help_text='Facility ground elevation, in meters', null=True, verbose_name='AMSL (meters)'),
        ),
        migrations.AlterField(
            model_name='preliminaryfacility',
            name='antenna_model_number',
            field=models.CharField(blank=True, help_text='Antenna Model Number', max_length=256, null=True, verbose_name='Antenna Model No.'),
        ),
        migrations.AlterField(
            model_name='preliminaryfacility',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text='A physical location on the Earth', null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='preliminaryfacility',
            name='pcase',
            field=models.ForeignKey(help_text='The Preliminary Case that this Facility is being considered under', on_delete=django.db.models.deletion.CASCADE, related_name='pfacilities', to='cases.PreliminaryCase'),
        ),
        migrations.AlterField(
            model_name='preliminaryfacility',
            name='power_density_limit',
            field=models.FloatField(blank=True, help_text='???', null=True, verbose_name='Power Density Limit'),
        ),
        migrations.AlterField(
            model_name='preliminaryfacility',
            name='site_num',
            field=models.PositiveIntegerField(blank=True, help_text='???', null=True, verbose_name='Site #'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text='A physical location on the Earth', null=True, srid=4326),
        ),
    ]
