# Generated by Django 2.2.2 on 2019-06-20 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_casegroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='case_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='cases.CaseGroup'),
        ),
    ]
