# Generated by Django 2.1.5 on 2019-02-06 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_add_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='original_index',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
