# Generated by Django 2.2.2 on 2019-06-21 20:38

import cases.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_case_case_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='FancyCaseGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('comments', cases.models.SensibleTextField(blank=True)),
                ('cases', models.ManyToManyField(blank=True, related_name='case_groups', to='cases.Case')),
                ('pcases', models.ManyToManyField(blank=True, related_name='case_groups', to='cases.PreliminaryCase')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
