# Generated by Django 2.1.5 on 2019-02-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('cases', '0006_facility_attachments'), ('cases', '0007_no_require_attachment_comments'), ('cases', '0008_preliminaryfacility_attachments')]

    dependencies = [
        ('cases', '0005_attachment_original_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='attachments',
            field=models.ManyToManyField(blank=True, related_name='facilities', to='cases.Attachment'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='preliminaryfacility',
            name='attachments',
            field=models.ManyToManyField(blank=True, related_name='prelim_facilities', to='cases.Attachment'),
        ),
    ]
