# Generated by Django 2.2.2 on 2019-06-24 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_auto_20190621_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preliminarycase',
            name='case',
        ),
    ]
