# Generated by Django 2.1.5 on 2019-02-07 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_add_attachments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facility',
            old_name='tap',
            new_name='tpa',
        ),
        migrations.AddField(
            model_name='case',
            name='agency_num',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='date_recorded',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Recorded'),
        ),
        migrations.AlterField(
            model_name='case',
            name='si_done',
            field=models.DateField(blank=True, null=True, verbose_name='SI Done'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='dominant_path',
            field=models.CharField(blank=True, choices=[('diffraction', 'Diffraction'), ('scatter', 'Scatter'), ('free_space', 'Free Space')], max_length=256, verbose_name='Dominant Path'),
        ),
    ]
