# Generated by Django 2.2.2 on 2019-06-24 22:28

import cases.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_remove_preliminarycase_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='casegroup',
            name='name',
            field=cases.models.SensibleCharField(blank=True, max_length=256),
        ),
    ]
