# Generated by Django 2.1.5 on 2019-02-13 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gis', '__first__'),
        ('cases', '0007_add_fields_for_nrqz_analyzer'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='location_description',
            field=models.CharField(blank=True, help_text='A long-form description of the facility location', max_length=512, null=True, verbose_name='Location Description'),
        ),
        migrations.AddField(
            model_name='facility',
            name='srid_used_for_import',
            field=models.ForeignKey(blank=True, help_text='The spatial reference system of the original imported coordinates', null=True, on_delete=django.db.models.deletion.PROTECT, to='gis.PostGISSpatialRefSys'),
        ),
        migrations.AddField(
            model_name='preliminaryfacility',
            name='location_description',
            field=models.CharField(blank=True, help_text='A long-form description of the facility location', max_length=512, null=True, verbose_name='Location Description'),
        ),
        migrations.AddField(
            model_name='preliminaryfacility',
            name='srid_used_for_import',
            field=models.ForeignKey(blank=True, help_text='The spatial reference system of the original imported coordinates', null=True, on_delete=django.db.models.deletion.PROTECT, to='gis.PostGISSpatialRefSys'),
        ),
    ]
