# Generated by Django 2.2.3 on 2019-07-16 19:42

from django.db import migrations
import django_import_data.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0010_auto_20190716_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file_path',
            field=django_import_data.mixins.SensibleCharField(default=None, help_text='Path to the file that this is linked to', max_length=512, unique=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='hash_on_disk',
            field=django_import_data.mixins.SensibleCharField(blank=True, help_text='SHA-1 hash of the file on disk. If blank, the file is missing', max_length=40, null=True, unique=True),
        ),
    ]
