# Generated by Django 2.1.5 on 2019-02-13 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("cases", "0010_usgs_dataset")]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="emission1",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="facility",
            name="emission2",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
