# Generated by Django 2.1.5 on 2019-02-13 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("cases", "0011_add_emission_fields")]

    operations = [
        migrations.AlterField(
            model_name="facility",
            name="srid_used_for_import",
            field=models.ForeignKey(
                default=-1,
                help_text="The spatial reference system of the original imported coordinates",
                on_delete=django.db.models.deletion.PROTECT,
                to="gis.PostGISSpatialRefSys",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="preliminaryfacility",
            name="srid_used_for_import",
            field=models.ForeignKey(
                default=-1,
                help_text="The spatial reference system of the original imported coordinates",
                on_delete=django.db.models.deletion.PROTECT,
                to="gis.PostGISSpatialRefSys",
            ),
            preserve_default=False,
        ),
    ]
