# Generated by Django 2.1.5 on 2019-02-13 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0012_make_sgrs_used_for_import_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='s367',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
