# Generated by Django 2.2.4 on 2019-08-26 14:35

from django.db import migrations, models
import django_import_data.mixins


def make_sgrs_service_num_null(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Case = apps.get_model("cases", "Case")
    db_alias = schema_editor.connection.alias
    Case.objects.using(db_alias).filter(sgrs_service_num=None).update(
        sgrs_service_num=""
    )


class Migration(migrations.Migration):

    dependencies = [("cases", "0013_sgrs_service_num_to_char_field")]

    operations = [
        migrations.RunPython(make_sgrs_service_num_null),
        migrations.AlterField(
            model_name="case",
            name="sgrs_service_num",
            field=django_import_data.mixins.SensibleCharField(
                blank=True,
                default="",
                help_text="SGRS Service Num.",
                max_length=256,
                verbose_name="SGRS Service #",
            ),
            preserve_default=False,
        ),
    ]
