# Generated by Django 2.1.5 on 2019-02-14 00:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0013_facility_s367'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='emission1',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='emission2',
        ),
        migrations.AddField(
            model_name='facility',
            name='emissions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='facility',
            name='s367',
            field=models.BooleanField(default=False),
        ),
    ]
