# Generated by Django 2.1.5 on 2019-02-14 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0014_auto_20190213_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='calc_az',
        ),
        migrations.AddField(
            model_name='facility',
            name='sgrs_responded_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='SGRS Responded On'),
        ),
    ]
