# Generated by Django 2.1.5 on 2019-02-14 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0015_auto_20190213_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='preliminaryfacility',
            name='tpa',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
