# Generated by Django 2.1.5 on 2019-02-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0016_preliminaryfacility_tpa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alsoknownas',
            options={'verbose_name': 'Also Known As', 'verbose_name_plural': 'Also Known As'},
        ),
        migrations.AlterModelOptions(
            name='attachment',
            options={'verbose_name': 'Attachment', 'verbose_name_plural': 'Attachments'},
        ),
        migrations.AlterModelOptions(
            name='boundaries',
            options={'verbose_name': 'Boundaries', 'verbose_name_plural': 'Boundaries'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Person', 'verbose_name_plural': 'People'},
        ),
        migrations.AddField(
            model_name='preliminaryfacility',
            name='nrqz_id',
            field=models.CharField(blank=True, db_index=True, help_text='Assigned by NRAO. Do not put any of your data in this column.', max_length=256, null=True, verbose_name='NRQZ ID'),
        ),
    ]
