# Generated by Django 2.2.5 on 2019-10-07 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0017_auto_20191007_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facilities', to='cases.Case'),
        ),
        migrations.AlterField(
            model_name='preliminaryfacility',
            name='pcase',
            field=models.ForeignKey(help_text='The Preliminary Case that this Facility is being considered under', on_delete=django.db.models.deletion.PROTECT, related_name='pfacilities', to='cases.PreliminaryCase'),
        ),
    ]
