# Generated by Django 2.1.5 on 2019-02-14 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0017_auto_20190214_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='nrao_aerpd_analog',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='nrao_aerpd_cdma',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='nrao_aerpd_cdma2000',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='nrao_aerpd_emission',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='nrao_aerpd_gsm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='nrao_diff',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='nrao_space',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='nrao_tropo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='original_outside_nrqz',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='radio_service',
            field=models.CharField(blank=True, max_length=256, verbose_name='Radio Service'),
        ),
        migrations.AddField(
            model_name='facility',
            name='survey_1a',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='survey_2c',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='topo_12_point',
            field=models.BooleanField(blank=True, null=True, verbose_name='Weighted 12 Point'),
        ),
        migrations.AddField(
            model_name='facility',
            name='topo_4_point',
            field=models.BooleanField(blank=True, null=True, verbose_name='FCC 4 Point'),
        ),
        migrations.AddField(
            model_name='preliminarycase',
            name='date_recorded',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Recorded'),
        ),
        migrations.AddField(
            model_name='preliminaryfacility',
            name='az_bearing',
            field=models.CharField(blank=True, help_text='The Azimuth bearing between the Facility and the GBT, as imported from existing data', max_length=256, null=True, verbose_name='AZ bearing degrees True'),
        ),
        migrations.AddField(
            model_name='preliminaryfacility',
            name='erpd_per_num_tx',
            field=models.CharField(blank=True, max_length=256, verbose_name='ERPd per # of Transmitters'),
        ),
        migrations.AddField(
            model_name='preliminaryfacility',
            name='nrao_aerpd_analog',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preliminaryfacility',
            name='nrao_aerpd_cdma',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preliminaryfacility',
            name='nrao_aerpd_cdma2000',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preliminaryfacility',
            name='nrao_aerpd_emission',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preliminaryfacility',
            name='nrao_aerpd_gsm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preliminaryfacility',
            name='nrao_diff',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preliminaryfacility',
            name='nrao_space',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preliminaryfacility',
            name='nrao_tropo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preliminaryfacility',
            name='original_outside_nrqz',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preliminaryfacility',
            name='radio_service',
            field=models.CharField(blank=True, max_length=256, verbose_name='Radio Service'),
        ),
        migrations.AddField(
            model_name='preliminaryfacility',
            name='survey_1a',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preliminaryfacility',
            name='survey_2c',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preliminaryfacility',
            name='topo_12_point',
            field=models.BooleanField(blank=True, null=True, verbose_name='Weighted 12 Point'),
        ),
        migrations.AddField(
            model_name='preliminaryfacility',
            name='topo_4_point',
            field=models.BooleanField(blank=True, null=True, verbose_name='FCC 4 Point'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='tpa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='uses_cross_polarization',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Uses Cross polarization '),
        ),
        migrations.AlterField(
            model_name='facility',
            name='uses_quad_or_octal_polarization',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Uses Quad or Octal polarization'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='uses_split_sectorization',
            field=models.BooleanField(blank=True, default=False, help_text='This facility uses split sectorization or dual-beam sectorization', null=True, verbose_name='Uses Split Sectorization'),
        ),
        migrations.AlterField(
            model_name='preliminaryfacility',
            name='tpa',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
