# Generated by Django 2.1.5 on 2019-02-15 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0018_auto_20190214_1822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facility',
            old_name='srid_used_for_import',
            new_name='original_srs',
        ),
        migrations.RenameField(
            model_name='preliminaryfacility',
            old_name='srid_used_for_import',
            new_name='original_srs',
        ),
    ]
