# Generated by Django 2.2.6 on 2019-10-08 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0018_protect_case'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='date_recorded',
            new_name='date_received',
        ),
        migrations.RenameField(
            model_name='preliminarycase',
            old_name='date_recorded',
            new_name='date_received',
        ),
    ]
