# Generated by Django 2.2.6 on 2019-10-08 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0019_date_recorded_to_date_received'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='date_received',
            field=models.DateField(blank=True, null=True, verbose_name='Date Received'),
        ),
        migrations.AlterField(
            model_name='preliminarycase',
            name='date_received',
            field=models.DateField(blank=True, null=True, verbose_name='Date Received'),
        ),
    ]
