# Generated by Django 2.1.5 on 2019-02-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0019_auto_20190215_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='preliminaryfacility',
            name='freq_high',
            field=models.FloatField(blank=True, help_text='Frequency specific or upper part of band.', null=True, verbose_name='Freq High (MHz)'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='electrical_downtilt',
            field=models.CharField(blank=True, help_text='Specific and/or RET range', max_length=256, verbose_name='Electrical Downtilt'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='location_description',
            field=models.CharField(blank=True, help_text='A long-form description of the facility location', max_length=512, null=True, verbose_name='Geographic Location'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='mechanical_downtilt',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Mechanical Downtilt'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='preliminaryfacility',
            name='location_description',
            field=models.CharField(blank=True, help_text='A long-form description of the facility location', max_length=512, null=True, verbose_name='Geographic Location'),
        ),
    ]
