# Generated by Django 2.2.6 on 2019-10-29 15:32

from django.db import migrations, models
import django_import_data.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0020_date_received_tweaks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='distance_to_first_obstacle',
            field=django_import_data.mixins.SensibleCharField(blank=True, max_length=256, verbose_name='Distance to First Obstacle (km)'),
        ),
        migrations.AlterField(
            model_name='lettertemplate',
            name='path',
            field=models.FilePathField(help_text="Save new files into '/home/sandboxes/tchamber/repos/nrqz_admin/letter_templates' in order to select them here", match='^[^~].*\\.docx$', max_length=512, path='/home/sandboxes/tchamber/repos/nrqz_admin/letter_templates', unique=True),
        ),
    ]
