# Generated by Django 2.1.5 on 2019-02-15 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0020_auto_20190215_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='propagation_model',
            field=models.CharField(default='Rounded Obstacle', max_length=256, verbose_name='Propagation Model'),
        ),
        migrations.AddField(
            model_name='preliminaryfacility',
            name='propagation_model',
            field=models.CharField(default='Rounded Obstacle', max_length=256, verbose_name='Propagation Model'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='antenna_model_number',
            field=models.CharField(blank=True, help_text='Antenna Model Number', max_length=256, null=True, verbose_name='Antenna Model No.'),
        ),
    ]
