# Generated by Django 2.2.8 on 2020-03-03 16:41

from django.db import migrations
import django_import_data.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0021_auto_20191029_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='agency_num',
            field=django_import_data.mixins.SensibleCharField(blank=True, help_text='Agency Num.', max_length=256, verbose_name='Agency #'),
        ),
        migrations.AddField(
            model_name='preliminaryfacility',
            name='agency_num',
            field=django_import_data.mixins.SensibleCharField(blank=True, help_text='Agency Num.', max_length=256, verbose_name='Agency #'),
        ),
        migrations.AlterField(
            model_name='case',
            name='agency_num',
            field=django_import_data.mixins.SensibleCharField(blank=True, help_text='Agency Num.', max_length=256, verbose_name='Agency #'),
        ),
    ]
