# Generated by Django 2.1.5 on 2019-02-15 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0021_auto_20190215_1115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facility',
            old_name='max_erp_per_tx',
            new_name='requested_max_erp_per_tx',
        ),
        migrations.RemoveField(
            model_name='case',
            name='name',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='asr_is_from_applicant',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='erpd_per_num_tx',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='max_output',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='nrao_aerpd_emission',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='num_quad_or_octal_ports_with_feed_power',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='technology',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='tx_antennas_per_sector',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='tx_power_neg_45',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='tx_power_pos_45',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='uses_cross_polarization',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='uses_quad_or_octal_polarization',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='uses_split_sectorization',
        ),
        migrations.RemoveField(
            model_name='preliminarycase',
            name='name',
        ),
        migrations.RemoveField(
            model_name='preliminaryfacility',
            name='erpd_per_num_tx',
        ),
        migrations.RemoveField(
            model_name='preliminaryfacility',
            name='nrao_aerpd_emission',
        ),
        migrations.AddField(
            model_name='facility',
            name='max_eirp',
            field=models.FloatField(blank=True, null=True, verbose_name='Max AEiRP'),
        ),
        migrations.AddField(
            model_name='facility',
            name='requested_max_erpd_per_tx',
            field=models.CharField(blank=True, max_length=256, verbose_name='Max ERPd per TX'),
        ),
        migrations.AddField(
            model_name='preliminaryfacility',
            name='requested_max_erpd_per_tx',
            field=models.CharField(blank=True, max_length=256, verbose_name='Max ERPd per TX'),
        ),
        migrations.AlterField(
            model_name='case',
            name='erpd_limit',
            field=models.BooleanField(blank=True, default=False, verbose_name='ERPd Limit'),
        ),
        migrations.AlterField(
            model_name='case',
            name='is_federal',
            field=models.BooleanField(null=True, verbose_name='Gov.'),
        ),
        migrations.AlterField(
            model_name='case',
            name='num_sites',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Num. Facilities'),
        ),
        migrations.AlterField(
            model_name='case',
            name='si',
            field=models.BooleanField(blank=True, default=False, verbose_name='SI Req.'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='propagation_model',
            field=models.CharField(blank=True, default='Rounded Obstacle', max_length=256, verbose_name='Propagation Model'),
        ),
        migrations.AlterField(
            model_name='preliminarycase',
            name='is_federal',
            field=models.BooleanField(null=True, verbose_name='Gov.'),
        ),
        migrations.AlterField(
            model_name='preliminarycase',
            name='num_sites',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Num. Facilities'),
        ),
        migrations.AlterField(
            model_name='preliminaryfacility',
            name='propagation_model',
            field=models.CharField(blank=True, default='Rounded Obstacle', max_length=256, verbose_name='Propagation Model'),
        ),
    ]
