# Generated by Django 2.1.5 on 2019-02-15 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0022_auto_20190215_1741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preliminaryfacility',
            old_name='requested_max_erpd_per_tx',
            new_name='requested_max_erp_per_tx',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='requested_max_erpd_per_tx',
        ),
    ]
