# Generated by Django 2.2.23 on 2021-12-02 20:03

from django.db import migrations


def combine_names(apps, schema_editor):
    Site = apps.get_model("sites", "Site")
    site = Site.objects.first()
    if not site:
        Site.objects.create(name="nrqz.gb.nrao.edu", domain="nrqz.gb.nrao.edu")
    else:
        site.name = "nrqz.gb.nrao.edu"
        site.domain = "nrqz.gb.nrao.edu"
        site.save()


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0023_facility_sgrs_work_order_num"),
        ("sites", "0002_alter_domain_unique"),
    ]

    operations = [
        migrations.RunPython(combine_names),
    ]
