# Generated by Django 2.2.24 on 2021-12-21 15:46

from django.db import migrations, models
import django_import_data.mixins


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0024_update_sites_domain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="case_num",
            field=django_import_data.mixins.SensibleCharField(
                db_index=True,
                default=None,
                max_length=256,
                unique=True,
                verbose_name="Case Num.",
            ),
        ),
    ]
