# Generated by Django 2.2.24 on 2021-12-02 20:14

from django.db import migrations, models
import django_import_data.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0024_update_sites_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='requested_max_erp_per_tx',
            field=models.FloatField(blank=True, null=True, verbose_name='ERP / # Tx'),
        ),
        migrations.AlterField(
            model_name='lettertemplate',
            name='path',
            field=models.FilePathField(help_text="Save new files into '/home/code/nrqz/NRQZ Admin Data/Letter Templates/' in order to select them here", match='^[^~].*\\.docx$', max_length=512, path='/home/code/nrqz/NRQZ Admin Data/Letter Templates/', unique=True),
        ),
        migrations.AlterField(
            model_name='preliminaryfacility',
            name='requested_max_erp_per_tx',
            field=django_import_data.mixins.SensibleCharField(blank=True, max_length=256, verbose_name='ERP / # Tx'),
        ),
    ]
