# Generated by Django 2.1.5 on 2019-02-26 20:19

import cases.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0024_auto_20190221_1259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facility',
            old_name='nrao_approval',
            new_name='meets_erpd_limit',
        ),
        migrations.RemoveField(
            model_name='case',
            name='erpd_limit',
        ),
        migrations.AddField(
            model_name='case',
            name='original_meets_erpd_limit',
            field=models.BooleanField(blank=True, default=False, verbose_name='Original ERPd Limit'),
        ),
        migrations.AlterField(
            model_name='case',
            name='agency_num',
            field=models.CharField(blank=True, help_text='Agency Num.', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_num',
            field=models.PositiveIntegerField(db_index=True, default=cases.models.get_case_num, unique=True, verbose_name='Case Num.'),
        ),
        migrations.AlterField(
            model_name='case',
            name='fcc_file_num',
            field=models.CharField(blank=True, max_length=256, verbose_name='FCC ULS Num.'),
        ),
        migrations.AlterField(
            model_name='case',
            name='freq_coord',
            field=models.CharField(blank=True, max_length=256, verbose_name='Freq. Coord. Num.'),
        ),
        migrations.AlterField(
            model_name='case',
            name='sgrs_service_num',
            field=models.PositiveIntegerField(blank=True, help_text='SGRS Service Num.', null=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='fcc_file_number',
            field=models.CharField(blank=True, help_text='???', max_length=256, null=True, verbose_name='FCC ULS Number'),
        ),
        migrations.AlterField(
            model_name='preliminarycase',
            name='case_num',
            field=models.PositiveIntegerField(db_index=True, default=cases.models.get_pcase_num, unique=True, verbose_name='Prelim. Case Num.'),
        ),
    ]
