# Generated by Django 2.1.5 on 2019-02-26 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0025_auto_20190226_1037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facility',
            old_name='nrao_approval',
            new_name='meets_erpd_limit',
        ),
        migrations.RemoveField(
            model_name='case',
            name='erpd_limit',
        ),
        migrations.AddField(
            model_name='case',
            name='original_erpd_limit',
            field=models.BooleanField(blank=True, default=False, verbose_name='Original ERPd Limit'),
        ),
        migrations.AlterField(
            model_name='case',
            name='fcc_file_num',
            field=models.CharField(blank=True, max_length=256, verbose_name='FCC ULS Num.'),
        ),
        migrations.AlterField(
            model_name='case',
            name='freq_coord',
            field=models.CharField(blank=True, max_length=256, verbose_name='Freq. Coord. Num.'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='fcc_file_number',
            field=models.CharField(blank=True, help_text='???', max_length=256, null=True, verbose_name='FCC ULS Number'),
        ),
    ]
