# Generated by Django 2.1.5 on 2019-02-27 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0025_auto_20190226_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='propagation_study',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propagation_study_for_facilities', to='cases.Attachment'),
        ),
        migrations.AddField(
            model_name='preliminaryfacility',
            name='propagation_study',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propagation_study_for_pfacilities', to='cases.Attachment'),
        ),
    ]
