# Generated by Django 2.1.5 on 2019-02-26 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0026_auto_20190226_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='original_erpd_limit',
            new_name='original_meets_erpd_limit',
        ),
    ]
