# Generated by Django 2.1.5 on 2019-02-27 21:26

import cases.models
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0026_add_propagation_study'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alsoknownas',
            name='data_source',
            field=models.CharField(choices=[('web', 'Web'), ('excel', 'Excel'), ('access_prelim_technical', 'Access Prelim. Technical Table'), ('access_technical', 'Access Technical Table'), ('access_prelim_application', 'Access Prelim. Application Table'), ('access_application', 'Access Application Table'), ('nam_application', 'NRQZ Analyzer Application'), ('fcc_asr', 'FCC ASR Database')], default=None, help_text='The source that this object was created from', max_length=25),
        ),
        migrations.AlterField(
            model_name='alsoknownas',
            name='name',
            field=cases.models.SensibleCharField(default=None, max_length=256),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='data_source',
            field=models.CharField(choices=[('web', 'Web'), ('excel', 'Excel'), ('access_prelim_technical', 'Access Prelim. Technical Table'), ('access_technical', 'Access Technical Table'), ('access_prelim_application', 'Access Prelim. Application Table'), ('access_application', 'Access Application Table'), ('nam_application', 'NRQZ Analyzer Application'), ('fcc_asr', 'FCC ASR Database')], default=None, help_text='The source that this object was created from', max_length=25),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='path',
            field=cases.models.SensibleCharField(default=None, max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='boundaries',
            name='bounds',
            field=django.contrib.gis.db.models.fields.PolygonField(geography=True, srid=4326, verbose_name='Bounds'),
        ),
        migrations.AlterField(
            model_name='boundaries',
            name='name',
            field=cases.models.SensibleCharField(default=None, max_length=64, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='case',
            name='agency_num',
            field=cases.models.SensibleCharField(blank=True, default='', help_text='Agency Num.', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='case',
            name='call_sign',
            field=cases.models.SensibleCharField(blank=True, max_length=256, verbose_name='Call Sign'),
        ),
        migrations.AlterField(
            model_name='case',
            name='data_source',
            field=models.CharField(choices=[('web', 'Web'), ('excel', 'Excel'), ('access_prelim_technical', 'Access Prelim. Technical Table'), ('access_technical', 'Access Technical Table'), ('access_prelim_application', 'Access Prelim. Application Table'), ('access_application', 'Access Application Table'), ('nam_application', 'NRQZ Analyzer Application'), ('fcc_asr', 'FCC ASR Database')], default=None, help_text='The source that this object was created from', max_length=25),
        ),
        migrations.AlterField(
            model_name='case',
            name='fcc_file_num',
            field=cases.models.SensibleCharField(blank=True, max_length=256, verbose_name='FCC ULS Num.'),
        ),
        migrations.AlterField(
            model_name='case',
            name='freq_coord',
            field=cases.models.SensibleCharField(blank=True, max_length=256, verbose_name='Freq. Coord. Num.'),
        ),
        migrations.AlterField(
            model_name='case',
            name='radio_service',
            field=cases.models.SensibleCharField(blank=True, max_length=256, verbose_name='Radio Service'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='antenna_model_number',
            field=cases.models.SensibleCharField(blank=True, default='', help_text='Antenna Model Number', max_length=256, verbose_name='Antenna Model No.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facility',
            name='az_bearing',
            field=cases.models.SensibleCharField(blank=True, default='', help_text='The Azimuth bearing between the Facility and the GBT, as imported from existing data', max_length=256, verbose_name='AZ bearing degrees True'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facility',
            name='call_sign',
            field=cases.models.SensibleCharField(blank=True, default='', help_text='The radio call sign of the Facility', max_length=256, verbose_name='Call Sign'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facility',
            name='data_source',
            field=models.CharField(choices=[('web', 'Web'), ('excel', 'Excel'), ('access_prelim_technical', 'Access Prelim. Technical Table'), ('access_technical', 'Access Technical Table'), ('access_prelim_application', 'Access Prelim. Application Table'), ('access_application', 'Access Application Table'), ('nam_application', 'NRQZ Analyzer Application'), ('fcc_asr', 'FCC ASR Database')], default=None, help_text='The source that this object was created from', max_length=25),
        ),
        migrations.AlterField(
            model_name='facility',
            name='distance_to_first_obstacle',
            field=cases.models.SensibleCharField(blank=True, default='', max_length=256, verbose_name='Distance to First Obstacle'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facility',
            name='dominant_path',
            field=cases.models.SensibleCharField(blank=True, choices=[('diffraction', 'Diffraction'), ('scatter', 'Scatter'), ('free_space', 'Free Space')], max_length=256, verbose_name='Dominant Path'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='electrical_downtilt',
            field=cases.models.SensibleCharField(blank=True, help_text='Specific and/or RET range', max_length=256, verbose_name='Electrical Downtilt'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='emissions',
            field=django.contrib.postgres.fields.ArrayField(base_field=cases.models.SensibleCharField(default=None, max_length=64), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='facility',
            name='fcc_file_number',
            field=cases.models.SensibleCharField(blank=True, default='', help_text='???', max_length=256, verbose_name='FCC ULS Number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facility',
            name='latitude',
            field=cases.models.SensibleCharField(blank=True, default='', help_text='Latitude of site, in degrees', max_length=256, verbose_name='Latitude'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facility',
            name='loc',
            field=cases.models.SensibleCharField(blank=True, max_length=256, verbose_name='LOC'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text='A physical location on the Earth', null=True, srid=4326, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='location_description',
            field=cases.models.SensibleCharField(blank=True, default='', help_text='A long-form description of the facility location', max_length=512, verbose_name='Geographic Location'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facility',
            name='longitude',
            field=cases.models.SensibleCharField(blank=True, default='', help_text='Longitude of site, in degrees', max_length=256, verbose_name='Longitude'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facility',
            name='main_beam_orientation',
            field=cases.models.SensibleCharField(blank=True, help_text='or sectorized AZ bearings (in ° True NOT ° Magnetic)', max_length=256, verbose_name='Main Beam Orientation'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='mechanical_downtilt',
            field=cases.models.SensibleCharField(blank=True, max_length=256, verbose_name='Mechanical Downtilt'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='meets_erpd_limit',
            field=models.BooleanField(blank=True, help_text='Indicates whether NRAO approves of this Facility or not', null=True, verbose_name='Meets NRAO ERPd Limit'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='nrqz_id',
            field=cases.models.SensibleCharField(blank=True, db_index=True, default=None, help_text='Assigned by NRAO. Do not put any of your data in this column.', max_length=256, verbose_name='NRQZ ID'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='propagation_model',
            field=cases.models.SensibleCharField(blank=True, default='Rounded Obstacle', max_length=256, verbose_name='Propagation Model'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='radio_service',
            field=cases.models.SensibleCharField(blank=True, max_length=256, verbose_name='Radio Service'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='site_name',
            field=cases.models.SensibleCharField(blank=True, default='', help_text='What you call it! Include MCN and eNB information.', max_length=256, verbose_name='Site Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facility',
            name='tap_file',
            field=cases.models.SensibleCharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='facility',
            name='tx_per_sector',
            field=cases.models.SensibleCharField(blank=True, help_text="(or No. of RRH's ports with feed power", max_length=256, verbose_name='Total number of TXers per sector'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='usgs_dataset',
            field=cases.models.SensibleCharField(blank=True, choices=[('3m', '3m'), ('10m', '10m'), ('30m', '30m')], max_length=3),
        ),
        migrations.AlterField(
            model_name='lettertemplate',
            name='name',
            field=cases.models.SensibleCharField(default=None, max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=cases.models.SensibleCharField(default=None, max_length=64, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='city',
            field=cases.models.SensibleCharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='person',
            name='county',
            field=cases.models.SensibleCharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='person',
            name='data_source',
            field=models.CharField(choices=[('web', 'Web'), ('excel', 'Excel'), ('access_prelim_technical', 'Access Prelim. Technical Table'), ('access_technical', 'Access Technical Table'), ('access_prelim_application', 'Access Prelim. Application Table'), ('access_application', 'Access Application Table'), ('nam_application', 'NRQZ Analyzer Application'), ('fcc_asr', 'FCC ASR Database')], default=None, help_text='The source that this object was created from', max_length=25),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='fax',
            field=cases.models.SensibleCharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=cases.models.SensibleCharField(default=None, max_length=256),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=cases.models.SensibleCharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='person',
            name='state',
            field=cases.models.SensibleCharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='person',
            name='street',
            field=cases.models.SensibleCharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='person',
            name='zipcode',
            field=cases.models.SensibleCharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='preliminarycase',
            name='data_source',
            field=models.CharField(choices=[('web', 'Web'), ('excel', 'Excel'), ('access_prelim_technical', 'Access Prelim. Technical Table'), ('access_technical', 'Access Technical Table'), ('access_prelim_application', 'Access Prelim. Application Table'), ('access_application', 'Access Application Table'), ('nam_application', 'NRQZ Analyzer Application'), ('fcc_asr', 'FCC ASR Database')], default=None, help_text='The source that this object was created from', max_length=25),
        ),
        migrations.AlterField(
            model_name='preliminarycase',
            name='radio_service',
            field=cases.models.SensibleCharField(blank=True, max_length=256, verbose_name='Radio Service'),
        ),
        migrations.AlterField(
            model_name='preliminarycasegroup',
            name='data_source',
            field=models.CharField(choices=[('web', 'Web'), ('excel', 'Excel'), ('access_prelim_technical', 'Access Prelim. Technical Table'), ('access_technical', 'Access Technical Table'), ('access_prelim_application', 'Access Prelim. Application Table'), ('access_application', 'Access Application Table'), ('nam_application', 'NRQZ Analyzer Application'), ('fcc_asr', 'FCC ASR Database')], default=None, help_text='The source that this object was created from', max_length=25),
        ),
        migrations.AlterField(
            model_name='preliminaryfacility',
            name='antenna_model_number',
            field=cases.models.SensibleCharField(blank=True, default='', help_text='Antenna Model Number', max_length=256, verbose_name='Antenna Model No.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='preliminaryfacility',
            name='az_bearing',
            field=cases.models.SensibleCharField(blank=True, default='', help_text='The Azimuth bearing between the Facility and the GBT, as imported from existing data', max_length=256, verbose_name='AZ bearing degrees True'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='preliminaryfacility',
            name='data_source',
            field=models.CharField(choices=[('web', 'Web'), ('excel', 'Excel'), ('access_prelim_technical', 'Access Prelim. Technical Table'), ('access_technical', 'Access Technical Table'), ('access_prelim_application', 'Access Prelim. Application Table'), ('access_application', 'Access Application Table'), ('nam_application', 'NRQZ Analyzer Application'), ('fcc_asr', 'FCC ASR Database')], default=None, help_text='The source that this object was created from', max_length=25),
        ),
        migrations.AlterField(
            model_name='preliminaryfacility',
            name='latitude',
            field=cases.models.SensibleCharField(blank=True, default='', help_text='Latitude of site, in degrees', max_length=256, verbose_name='Latitude'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='preliminaryfacility',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text='A physical location on the Earth', null=True, srid=4326, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='preliminaryfacility',
            name='location_description',
            field=cases.models.SensibleCharField(blank=True, default='', help_text='A long-form description of the facility location', max_length=512, verbose_name='Geographic Location'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='preliminaryfacility',
            name='longitude',
            field=cases.models.SensibleCharField(blank=True, default='', help_text='Longitude of site, in degrees', max_length=256, verbose_name='Longitude'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='preliminaryfacility',
            name='nrqz_id',
            field=cases.models.SensibleCharField(blank=True, db_index=True, default=None, help_text='Assigned by NRAO. Do not put any of your data in this column.', max_length=256, verbose_name='NRQZ ID'),
        ),
        migrations.AlterField(
            model_name='preliminaryfacility',
            name='propagation_model',
            field=cases.models.SensibleCharField(blank=True, default='Rounded Obstacle', max_length=256, verbose_name='Propagation Model'),
        ),
        migrations.AlterField(
            model_name='preliminaryfacility',
            name='radio_service',
            field=cases.models.SensibleCharField(blank=True, max_length=256, verbose_name='Radio Service'),
        ),
        migrations.AlterField(
            model_name='preliminaryfacility',
            name='requested_max_erp_per_tx',
            field=cases.models.SensibleCharField(blank=True, max_length=256, verbose_name='Max ERPd per TX'),
        ),
        migrations.AlterField(
            model_name='preliminaryfacility',
            name='site_name',
            field=cases.models.SensibleCharField(blank=True, default='', help_text='What you call it! Include MCN and eNB information.', max_length=256, verbose_name='Site Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='preliminaryfacility',
            name='usgs_dataset',
            field=cases.models.SensibleCharField(blank=True, choices=[('3m', '3m'), ('10m', '10m'), ('30m', '30m')], max_length=3),
        ),
        migrations.AlterField(
            model_name='structure',
            name='data_source',
            field=models.CharField(choices=[('web', 'Web'), ('excel', 'Excel'), ('access_prelim_technical', 'Access Prelim. Technical Table'), ('access_technical', 'Access Technical Table'), ('access_prelim_application', 'Access Prelim. Application Table'), ('access_application', 'Access Application Table'), ('nam_application', 'NRQZ Analyzer Application'), ('fcc_asr', 'FCC ASR Database')], default=None, help_text='The source that this object was created from', max_length=25),
        ),
        migrations.AlterField(
            model_name='structure',
            name='faa_circ_num',
            field=cases.models.SensibleCharField(default=None, max_length=256, verbose_name='FAA Circulation Number'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='faa_study_num',
            field=cases.models.SensibleCharField(default=None, max_length=256, verbose_name='FAA Study Number'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='file_num',
            field=cases.models.SensibleCharField(default=None, max_length=256, verbose_name='File Number'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text='A physical location on the Earth', null=True, srid=4326, verbose_name='Location'),
        ),
    ]
