# Generated by Django 2.1.5 on 2019-02-28 16:50

import cases.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0030_sensible_text_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=cases.models.SensibleEmailField(blank=True, max_length=254),
        ),
    ]
