# Generated by Django 2.2.1 on 2019-05-28 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0031_sensible_email_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='model_import_attempt',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_import_data.ModelImportAttempt'),
        ),
        migrations.AlterField(
            model_name='case',
            name='model_import_attempt',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_import_data.ModelImportAttempt'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='model_import_attempt',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_import_data.ModelImportAttempt'),
        ),
        migrations.AlterField(
            model_name='person',
            name='model_import_attempt',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_import_data.ModelImportAttempt'),
        ),
        migrations.AlterField(
            model_name='preliminarycase',
            name='model_import_attempt',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_import_data.ModelImportAttempt'),
        ),
        migrations.AlterField(
            model_name='preliminarycasegroup',
            name='model_import_attempt',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_import_data.ModelImportAttempt'),
        ),
        migrations.AlterField(
            model_name='preliminaryfacility',
            name='model_import_attempt',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_import_data.ModelImportAttempt'),
        ),
    ]
