# Generated by Django 2.2.1 on 2019-05-29 15:06

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0033_person_other_field_values'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='other_field_values',
            new_name='alias_field_values',
        ),
        migrations.AddField(
            model_name='person',
            name='alias_field_values_summary',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
