# Generated by Django 2.2.1 on 2019-06-05 19:32

import cases.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0035_add_alias_field_values_to_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='lettertemplate',
            name='description',
            field=cases.models.SensibleTextField(blank=True),
        ),
    ]
