# Generated by Django 2.2.1 on 2019-06-05 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0036_lettertemplate_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlsoKnownAs',
        ),
    ]
