# Generated by Django 2.2.1 on 2019-06-07 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("django_super_deduper", "__first__"),
        ("cases", "0038_add_verbose_name_to_sgrs_approval"),
    ]

    operations = [
        migrations.RemoveField(model_name="person", name="alias_field_values"),
        migrations.RemoveField(model_name="person", name="alias_field_values_summary"),
        migrations.AddField(
            model_name="person",
            name="merge_info",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="django_super_deduper.MergeInfo",
            ),
        ),
    ]
