# Generated by Django 2.2.2 on 2019-06-07 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0039_migrate_to_merge_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='si_done',
            field=models.DateField(blank=True, null=True, verbose_name='SI Done'),
        ),
    ]
