# Generated by Django 2.2.1 on 2019-06-10 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0040_facility_si_done'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='si_done',
            new_name='original_si_done',
        ),
    ]
