graph TD
    subgraph Internal Application Methods
        access_app["Access-Based Application (deprecated)"]
    end

    subgraph Public Application Methods
        subgraph GBO-Provided
            nam_app[nrqzApplicationMaker-Based Application]
            excel_app[Excel-Based Application]
        end

        subgraph Non-GBO Standards
            fcc601_app[FCC 601]
        end
    end

    subgraph Internal Data Stores
        access_db[Access DB]
        nam_db[nrqzApplicationMaker Flat Files]
        excel_db[Excel Flat Files]
    end

    nam_app --> nam_db
    excel_app --> excel_db
    access_app --> access_db

    subgraph Outputs
        access_db --> reports[Reports]
        nam_db --> letter[Concurrence Letter]
    end
    
    fcc601_app -.-> excel_db
    nam_db -.-> reports
    excel_db -.-> reports
    access_db -.-> letter
    excel_db -.-> letter

