sequenceDiagram
    participant applicant as Applicant
    participant admin as NRQZ Admin
    participant excel_master as "Master Spreadsheet"
    participant tap as TAP: Terrain Analysis Package

    applicant-->>admin: Emails a completed AutoPath Template
    admin->>excel_master: Admin copies all data into a copy of the "master spreadsheet"
    excel_master->>tap: Certain values must be calculated by TAP...
    tap->>excel_master: ...and then manually put into the spreadsheet
